# modules/local/sample_candidates/pyproject.toml

[project]
name = "sample-candidates"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
  "duckdb>=1.5.4",
  "polars>=1.42.1",
  "pyarrow>=24.0.0",
  "rdkit>=2026.3.3",
]

[project.scripts]
sample-candidates = "sample_candidates.sample_candidates:sample_candidates"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"
