# modules/local/sample_candidates/pyproject.toml

[project]
name = "sample-candidates"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.2",
    "duckdb>=1.5.4",
    "numpy>=2.5.1",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "lynceus-utils",
]

[project.scripts]
sample-candidates = "sample_candidates.cli:sample_candidates"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
lynceus-utils = { workspace = true }
