---
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        language: system
        types: [python]
      - id: yamllint
        name: yamllint
        entry: uv run yamllint .
        language: system
        types: [yaml]
