# pyproject.toml

[project]
name = "lynceus-dev"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = [
    # libs
    "lynceus-chem",
    "protein-conformational-ensemble",
    # utils
    "detect-putative-binding-sites",
    "physiochemical-filter",
    "sample-candidates",
]

[tool.uv.workspace]
members = [
    # libs
    "libs/lynceus-chem",
    "libs/protein-conformational-ensemble",
    # utils
    "modules/local/detect_putative_binding_sites",
    "modules/local/physiochemical_filter",
    "modules/local/sample_candidates",
]

[tool.uv.sources]
lynceus-chem = { workspace = true }
protein-conformational-ensemble = { workspace = true }

physiochemical-filter = { workspace = true }
sample-candidates = { workspace = true }
detect-putative-binding-sites = { workspace = true }

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "mypy>=2.2.0",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "ruff>=0.15.21",
    "yamllint>=1.38.0",
    "pre-commit>=4.6.0",
]
