[project]
name = "lynceus-dev"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = ["physiochemical-filter", "preprocess-candidates"]

[tool.uv.workspace]
members = [
    "libs/*",
    "modules/local/preprocess_candidates",
    "modules/local/physiochemical_filter",
    "modules/local/sample_candidates",
]

[tool.uv.sources]
preprocess-candidates = { workspace = true }
physiochemical-filter = { workspace = true }

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "mypy>=2.2.0",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "ruff>=0.15.21",
    "yamllint>=1.38.0",
    "pre-commit>=4.6.0",
]
