---
storage:
  bucket: lynceus
  prefixes:
    candidates:
      raw_smiles: candidates/raw/smiles
      raw_parquet: candidates/raw/parquet
      shards_staging: candidates/shards_staging
      shards: candidates/shards
      shards_sample: candidates/shards_sample

candidates:
  num_shards: 512

templates:
  default:
    requests:
      cpu: "4"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 4Gi
