---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-driver
  namespace: lynceus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nf-driver
  template:
    metadata:
      labels:
        app: nf-driver
    spec:
      serviceAccountName: nextflow-sa
      imagePullSecrets:
        - name: zot-registry-creds
      containers:
        - name: nextflow
          image: registry.nebula.local:8080/lynceus/nf-driver:0.1.0
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: garage-s3-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-s3-creds
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: work
              mountPath: /workspace
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: lynceus-work-pvc
