---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lynceus-work
  namespace: lynceus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
