---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-sa
  namespace: lynceus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-pod-manager
  namespace: lynceus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-pod-manager-binding
  namespace: lynceus
subjects:
  - kind: ServiceAccount
    name: nextflow-sa
    namespace: lynceus
roleRef:
  kind: Role
  name: nextflow-pod-manager
  apiGroup: rbac.authorization.k8s.io
