[project]
name = "preprocess-candidates"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.2",
    "numpy>=2.5.1",
    "polars>=1.42.1",
    "pyarrow>=24.0.0",
    "rdkit>=2026.3.4",
    "dimorphite-dl",
]

[project.scripts]
preprocess-candidates = "preprocess_candidates.cli:preprocess"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
dimorphite-dl = { git = "https://github.com/mmicatka/dimorphite_dl.git" }
