# modules/local/docking_prep/docking-prep/pyproject.toml

[project]
name = "docking-prep"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Mike", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["gemmi>=0.7.5", "meeko>=0.7.1", "prody>=2.6.1", "scipy>=1.18.0"]

[project.scripts]
docking-prepare-ensemble = "docking_prep.prepare_ensemble:prepare_ensemble"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"
