# modules/local/generate_pce_manifest/pyproject.toml

[project]
name = "generate-pce-manifest"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.2",
    "lynceus-utils",
    "protein-conformational-ensemble",
]


[project.scripts]
generate-pce-manifest = "generate_pce_manifest.cli:generate_pce_manifest"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
protein-conformational-ensemble = { workspace = true }
lynceus-utils = { workspace = true }
