# modules/local/generate_manifest/pyproject.toml

[project]
name = "generate-manifest"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = ["protein-conformational-ensemble"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["src"]
packages = ["src/generate_manifest"]

[tool.uv.sources]
protein-conformational-ensemble = { workspace = true }
