apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 10m-poc-candidates-
spec:
  entrypoint: main-dag
  serviceAccountName: argo-workflow
  templates:
  - name: main-dag
    dag:
      tasks:
      - name: load-candidates
        template: load-candidates
        withItems:
        - H04
        - H05
        - H06
        - H07
        - H08
        - H09
        - H10
        - H11
        - H12
        - H13
        - H14
        - H15
        - H16
        - H17
        - H18
        - H19
        - H20
        - H21
        - H22
        - H23
        - H24
        - H25
        - H26
        - H27
        - H28
        arguments:
          parameters:
          - name: source
            value: '{{item}}'
          - name: mount_path
            value: /mnt/data
          - name: source_prefix
            value: candidates/raw/smiles
          - name: parquet_prefix
            value: candidates/raw/parquet
  - name: load-candidates
    volumes:
    - name: lynceus-data
      persistentVolumeClaim:
        claimName: lynceus-bucket-pvc
    inputs:
      parameters:
      - name: source
      - name: mount_path
      - name: source_prefix
      - name: parquet_prefix
    script:
      image: registry.nebula.lan:5000/lynceus/candidates:0.1.0
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: mount_path = json.loads(r'''{{inputs.parameters.mount_path}}''')
        except: mount_path = r'''{{inputs.parameters.mount_path}}'''
        try: parquet_prefix = json.loads(r'''{{inputs.parameters.parquet_prefix}}''')
        except: parquet_prefix = r'''{{inputs.parameters.parquet_prefix}}'''
        try: source = json.loads(r'''{{inputs.parameters.source}}''')
        except: source = r'''{{inputs.parameters.source}}'''
        try: source_prefix = json.loads(r'''{{inputs.parameters.source_prefix}}''')
        except: source_prefix = r'''{{inputs.parameters.source_prefix}}'''

        import os
        import subprocess
        subprocess.run(['load-candidates', '--input', os.path.join(mount_path, source_prefix, source), '--output', os.path.join(mount_path, parquet_prefix)], check=True)
      command:
      - python
      volumeMounts:
      - name: lynceus-data
        mountPath: /mnt/data
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '4'
          memory: 4Gi
