apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 10m-poc-candidates-
spec:
  entrypoint: main-dag
  serviceAccountName: argo-workflow
  templates:
  - name: process-source-dag
    dag:
      tasks:
      - name: load-candidates
        template: load-candidates
        arguments:
          parameters:
          - name: source
            value: '{{inputs.parameters.source}}'
          - name: mount_path
            value: /mnt/data
          - name: source_prefix
            value: candidates/raw/smiles
          - name: parquet_prefix
            value: candidates/raw/parquet/{{inputs.parameters.source}}
      - name: shard-candidates
        depends: load-candidates
        template: shard-candidates
        arguments:
          parameters:
          - name: mount_path
            value: /mnt/data
          - name: input_prefix
            value: candidates/raw/parquet/{{inputs.parameters.source}}
          - name: output_prefix
            value: candidates/shards_staging
          - name: num_shards
            value: '16'
    inputs:
      parameters:
      - name: source
  - name: load-candidates
    volumes:
    - name: lynceus
      persistentVolumeClaim:
        claimName: lynceus-workdir
    inputs:
      parameters:
      - name: source
      - name: mount_path
      - name: source_prefix
      - name: parquet_prefix
    retryStrategy:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    script:
      image: registry.nebula.lan:5000/lynceus-candidates:0.1.0
      imagePullPolicy: Always
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: mount_path = json.loads(r'''{{inputs.parameters.mount_path}}''')
        except: mount_path = r'''{{inputs.parameters.mount_path}}'''
        try: parquet_prefix = json.loads(r'''{{inputs.parameters.parquet_prefix}}''')
        except: parquet_prefix = r'''{{inputs.parameters.parquet_prefix}}'''
        try: source = json.loads(r'''{{inputs.parameters.source}}''')
        except: source = r'''{{inputs.parameters.source}}'''
        try: source_prefix = json.loads(r'''{{inputs.parameters.source_prefix}}''')
        except: source_prefix = r'''{{inputs.parameters.source_prefix}}'''

        import os
        import subprocess
        subprocess.run(['load-candidates', '--input', os.path.join(mount_path, source_prefix, source), '--output', os.path.join(mount_path, parquet_prefix)], check=True)
      command:
      - python
      volumeMounts:
      - name: lynceus
        mountPath: /mnt/lynceus
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '4'
          memory: 4Gi
  - name: shard-candidates
    volumes:
    - name: lynceus
      persistentVolumeClaim:
        claimName: lynceus-workdir
    inputs:
      parameters:
      - name: mount_path
      - name: input_prefix
      - name: output_prefix
      - name: num_shards
      - name: id_column
        default: id
      - name: num_workers
        default: auto
    retryStrategy:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    script:
      image: registry.nebula.lan:5000/lynceus-candidates:0.1.0
      imagePullPolicy: Always
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: id_column = json.loads(r'''{{inputs.parameters.id_column}}''')
        except: id_column = r'''{{inputs.parameters.id_column}}'''
        try: input_prefix = json.loads(r'''{{inputs.parameters.input_prefix}}''')
        except: input_prefix = r'''{{inputs.parameters.input_prefix}}'''
        try: mount_path = json.loads(r'''{{inputs.parameters.mount_path}}''')
        except: mount_path = r'''{{inputs.parameters.mount_path}}'''
        try: num_shards = json.loads(r'''{{inputs.parameters.num_shards}}''')
        except: num_shards = r'''{{inputs.parameters.num_shards}}'''
        try: num_workers = json.loads(r'''{{inputs.parameters.num_workers}}''')
        except: num_workers = r'''{{inputs.parameters.num_workers}}'''
        try: output_prefix = json.loads(r'''{{inputs.parameters.output_prefix}}''')
        except: output_prefix = r'''{{inputs.parameters.output_prefix}}'''

        import os
        import subprocess
        subprocess.run(['shard-candidates', '--input', os.path.join(mount_path, input_prefix), '--output', os.path.join(mount_path, output_prefix), '--num-shards', str(num_shards), '--id-column', id_column, '--num-workers', str(num_workers)], check=True)
      command:
      - python
      volumeMounts:
      - name: lynceus
        mountPath: /mnt/lynceus
      resources:
        limits:
          cpu: '8'
          memory: 8Gi
        requests:
          cpu: '8'
          memory: 8Gi
  - name: main-dag
    parallelism: 2
    dag:
      tasks:
      - name: process-sources
        template: process-source-dag
        withItems:
        - H04
        - H05
        - H06
        - H07
        - H08
        - H09
        - H10
        - H11
        - H12
        - H13
        - H14
        - H15
        - H16
        - H17
        - H18
        - H19
        arguments:
          parameters:
          - name: source
            value: '{{item}}'
      - name: merge-shards
        depends: process-sources
        template: merge-shards
        withItems:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        arguments:
          parameters:
          - name: mount_path
            value: /mnt/data
          - name: input_path
            value: candidates/shards_staging/shard_id={{item}}
          - name: output_path
            value: candidates/shards/shard_{{item}}.parquet
      - name: cleanup-staging
        depends: merge-shards
        template: clean-prefix
        arguments:
          parameters:
          - name: mount_path
            value: /mnt/data
          - name: prefix
            value: candidates/shards_staging
      - name: subsample-candidates
        depends: cleanup-staging
        template: subsample-candidates
        withItems:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        arguments:
          parameters:
          - name: source
            value: shard_{{item}}.parquet
          - name: mount_path
            value: /mnt/data
          - name: source_prefix
            value: candidates/shards
          - name: parquet_prefix
            value: candidates/shards_sample/shard_{{item}}
          - name: num_samples
            value: '625000'
  - name: merge-shards
    volumes:
    - name: lynceus
      persistentVolumeClaim:
        claimName: lynceus-workdir
    inputs:
      parameters:
      - name: mount_path
      - name: input_path
      - name: output_path
      - name: num_workers
        default: auto
    retryStrategy:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    script:
      image: registry.nebula.lan:5000/lynceus-candidates:0.1.0
      imagePullPolicy: Always
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: input_path = json.loads(r'''{{inputs.parameters.input_path}}''')
        except: input_path = r'''{{inputs.parameters.input_path}}'''
        try: mount_path = json.loads(r'''{{inputs.parameters.mount_path}}''')
        except: mount_path = r'''{{inputs.parameters.mount_path}}'''
        try: num_workers = json.loads(r'''{{inputs.parameters.num_workers}}''')
        except: num_workers = r'''{{inputs.parameters.num_workers}}'''
        try: output_path = json.loads(r'''{{inputs.parameters.output_path}}''')
        except: output_path = r'''{{inputs.parameters.output_path}}'''

        import os
        import subprocess
        subprocess.run(['merge-shards', '--input', os.path.join(mount_path, input_path), '--output', os.path.join(mount_path, output_path), '--num-workers', str(num_workers)], check=True)
      command:
      - python
      volumeMounts:
      - name: lynceus
        mountPath: /mnt/lynceus
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '4'
          memory: 4Gi
  - name: clean-prefix
    volumes:
    - name: lynceus-data
      persistentVolumeClaim:
        claimName: lynceus-bucket-pvc
    container:
      image: alpine:3.20
      args:
      - test -n "$1" && rm -rf "$0/$1"
      - '{{inputs.parameters.mount_path}}'
      - '{{inputs.parameters.prefix}}'
      command:
      - sh
      - -c
      volumeMounts:
      - name: lynceus-data
        mountPath: /mnt/data
    inputs:
      parameters:
      - name: mount_path
      - name: prefix
  - name: subsample-candidates
    volumes:
    - name: lynceus
      persistentVolumeClaim:
        claimName: lynceus-workdir
    inputs:
      parameters:
      - name: source
      - name: mount_path
      - name: source_prefix
      - name: parquet_prefix
      - name: num_samples
    retryStrategy:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    script:
      image: registry.nebula.lan:5000/lynceus-candidates:0.1.0
      imagePullPolicy: Always
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: mount_path = json.loads(r'''{{inputs.parameters.mount_path}}''')
        except: mount_path = r'''{{inputs.parameters.mount_path}}'''
        try: num_samples = json.loads(r'''{{inputs.parameters.num_samples}}''')
        except: num_samples = r'''{{inputs.parameters.num_samples}}'''
        try: parquet_prefix = json.loads(r'''{{inputs.parameters.parquet_prefix}}''')
        except: parquet_prefix = r'''{{inputs.parameters.parquet_prefix}}'''
        try: source = json.loads(r'''{{inputs.parameters.source}}''')
        except: source = r'''{{inputs.parameters.source}}'''
        try: source_prefix = json.loads(r'''{{inputs.parameters.source_prefix}}''')
        except: source_prefix = r'''{{inputs.parameters.source_prefix}}'''

        import os
        import subprocess
        subprocess.run(['sample-candidates', '--input', os.path.join(mount_path, source_prefix, source), '--output', os.path.join(mount_path, parquet_prefix, source), '--num-samples', str(num_samples)], check=True)
      command:
      - python
      volumeMounts:
      - name: lynceus
        mountPath: /mnt/lynceus
      resources:
        limits:
          cpu: '4'
          memory: 4Gi
        requests:
          cpu: '4'
          memory: 4Gi
