---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lynceus-bucket-pvc
  namespace: workflows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  volumeName: lynceus-bucket-pv
