---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: REPLACE_ME_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: REPLACE_ME_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-role-binding
  namespace: REPLACE_ME_NAMESPACE
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: REPLACE_ME_NAMESPACE
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
