[project]
name = "generate-conformers"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "blake3>=1.0.9",
    "click>=8.4.2",
    "dimorphite-dl",
    "duckdb>=1.5.4",
    "lynceus-utils[s3]",
    "numpy>=2.5.1",
    "pyarrow>=24.0.0",
]


[project.scripts]
generate-conformers = "generate_conformers.cli:generate_conformers"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
dimorphite-dl = { git = "https://github.com/mmicatka/dimorphite_dl.git" }
lynceus-utils = { workspace = true }
