[project]
name = "rebalance-candidates"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["duckdb>=1.5.4", "pyarrow>=24.0.0"]

[project.scripts]
rebalance-candidates = "rebalance_candidates.cli:rebalance_candidates"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
