---
# conf/examples/dev.yaml

# uri_list: assets/candidate_uris.blackhole.txt
candidates_local_path: assets/.local/*

outdir: results/dev

filter:
  config: conf/examples/physiochemical_filter.yaml
  batch_size: 50000

surrogate_model:
  training:
    seed: 1000
    num_samples: 100000

target:
  ensemble:
    ensemble_id: "BACE1_4B70_static"
    type: "static"
    components:
      - pdb_id: "4B70"
        weight: 1.0
    # ensemble_id: "1STP_static_v1"
    # type: "static"
    # components:
    #   - pdb_id: "1STP"
    #     weight: 1.0

    capabilities_required:
      - "standalone_cif"
