---
# conf/examples/dev.yaml

# uri_list: assets/candidate_uris.blackhole.txt
candidates_local_path: assets/.local/*

outdir: results/dev

filter:
  config: conf/examples/physiochemical_filter.yaml
  batch_size: 1000

#### TARGET #####

target:
  ensemble:
    ensemble_id: "JAK2_static"
    type: "static"
    components:
      - pdb_id: "3FUP"
        weight: 1.0

    capabilities_required:
      - "standalone_cif"
