# modules/local/physiochemical_filter/pyproject.toml

[project]
name = "physiochemical-filter"
version = "0.1.0"
description = "Performs physiochemical-based filtering"
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.2",
    "duckdb>=1.5.4",
    "lynceus-utils",
    "pyarrow>=24.0.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
physiochemical-filter = "physiochemical_filter.physiochemical_filter:physiochemical_filter"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.uv.sources]
lynceus-utils = { workspace = true }
