# modules/local/physiochemical_filter/pyproject.toml

[project]
name = "physiochemical-filter"
version = "0.1.0"
description = "Performs physiochemical-based filtering"
requires-python = ">=3.12"
dependencies = ["duckdb>=1.5.4", "pyyaml>=6.0.3"]

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"

[tool.hatch.build.targets.wheel]
sources = ["src"]
packages = ["src/physiochemical_filter"]
