[project]
name = "lynceus-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "click>=8.4.2",
    "duckdb>=1.5.4",
    "pydantic>=2.13.5",
    "structlog>=26.1.0",
]

[project.scripts]
merge-shards = "lynceus_core:merge_shards"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
